import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ErrorBoundary from "@/components/ui/ErrorBoundary";
import AmplifyProvider from "./AmplifyProvider"; // 1. Import the provider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Invoice Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AmplifyProvider> {/* 2. Wrap the app with it */}
          <ErrorBoundary>
            {children}
          </ErrorBoundary>
        </AmplifyProvider>
      </body>
    </html>
  );
}
